/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CLIR.client.GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

import CLIR.server.Englisherrorc;

/**
 *
 * @author Administrator
 * 

 */
public class Eng_error extends javax.swing.JFrame {

    /**
     * Creates new form Hindi_errorcorrection
     * 
     */
	
	 
    public static void centreWindow(Window frame) {
  Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
  int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
  int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
  frame.setLocation(x, y);                     
    }  
    public Eng_error() {
        initComponents();
        centreWindow(this);
        eng_scroll.setVisible(false);
        eng_table.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        word_entry = new javax.swing.JTextField();
        enter_1 = new javax.swing.JButton();
        eng_scroll = new javax.swing.JScrollPane();
        eng_table = new javax.swing.JTable();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Word");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(37, 43, 60, 22);
        
      

        word_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                word_entryActionPerformed(evt);
            }
        });
        jPanel1.add(word_entry);
        word_entry.setBounds(100, 50, 180, 20);

        enter_1.setIcon(new javax.swing.ImageIcon("C:/Users/hp/workspace/CLIRserver1/src/CLIR/client/GUI/button.png")); // NOI18N
        enter_1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        enter_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					enter_1ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jPanel1.add(enter_1);
        enter_1.setBounds(260, 90, 90, 30);

        eng_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Suggested Word", "Edit Distance"
            }
        ));
        eng_scroll.setViewportView(eng_table);

        jPanel1.add(eng_scroll);
        eng_scroll.setBounds(20, 150, 340, 110);

        back.setIcon(new javax.swing.ImageIcon("C:/Users/hp/workspace/CLIRserver1/src/CLIR/client/GUI/red1.jpg")); // NOI18N
        jPanel1.add(back);
        back.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void word_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_word_entryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_word_entryActionPerformed

    private void enter_1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_enter_1ActionPerformed
        
        String wrd = word_entry.getText();
        
        String data[][] = {{}};
        String col[] = {"Suggested word",  "Edit distance"};
        DefaultTableModel t = new DefaultTableModel(data, col);
        Englisherrorc eec = new Englisherrorc();
        String[] lis = eec.correct(wrd);
        eng_table.setModel(t);
        eng_table.setModel(t);
        eng_scroll.setVisible(true);
        eng_table.setVisible(true);
        for(int i = 0; i < lis.length; i++) {
        	t.insertRow(0, new Object[]{lis[i], lis[i+1]});
        }
       
      
       // String g[][][] ={"ratna", "2", "3"} ;
        Map<String, String> res = new HashMap<String,String>();
        
        /*for (Map.Entry<String, String> entry : res.entrySet()) {
              String key = entry.getKey();
              String dist = entry.getValue();
              //String d = dist + "";
               t.insertRow(0, new Object[]{key, dist});
             // System.out.println("word = " + key + " dist = " + dist);  
           //  dis.put(key,d);
         }*/
       
       
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eng_error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eng_error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eng_error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eng_error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eng_error().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JScrollPane eng_scroll;
    private javax.swing.JTable eng_table;
    private javax.swing.JButton enter_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField word_entry;
    // End of variables declaration//GEN-END:variables
}
